name: CI

on:
  push:
  pull_request:

jobs:
  validate-and-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Validate Compose
        run: docker compose config

      - name: Build Containers
        run: docker compose build
